development:
  cloud_name: YOUR_DEV_CLOUD_NAME # Replace with your actual cloud name
  api_key:    YOUR_DEV_API_KEY    # Replace with your actual API key
  api_secret: YOUR_DEV_API_SECRET # Replace with your actual API secret
  secure: true

test:
  cloud_name: YOUR_TEST_CLOUD_NAME # Or use dev values if you don't have separate test cloud
  api_key:    YOUR_TEST_API_KEY
  api_secret: YOUR_TEST_API_SECRET
  secure: true

production:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key:    <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  secure: true
  # enhance_image_tag: true # Optional: enables more advanced features for image tags
  # static_file_support: false # Set to true if you want Cloudinary to serve static assets
